### ISSUE TITLE
Cleric rebirth scaling intentions

### ISSUE THREAD

**Issue by songdavid98** [aikaterna/gobcog#265] opened 2020-07-29 01:19 UTC
On line 6246 (and subsequently pray calculation lines), the code shows how cleric's pray is calculated. 

`+ ((mod * len(fight_list)) * max(c.rebirths * 0.01, 1.5))`

In the second half of this line ` max(c.rebirths * 0.01, 1.5)` suggests that clerics would have to get to rebirth 150 before their pray starts to scale, at which it scales +1% for each rebirth thereon out.

Getting to rebirth 150 seems a little ridiculous to me, so please let me know if this is intentional.
I theorize that the intention was to make the factor 0.1 instead of 0.01 since that would make clerics start scaling at rebirth 15. 

EDIT: 15 seems about right, since that's where the roll cap increases from 20 to 50.

**Comment by Drapersniper** [comment] 2020-07-29 07:42
Cleric scaling is working as intended

**Comment by Drapersniper** [comment] 2020-07-29 09:40
With that said there was a bug unrelated to what you stated here. which will be fixed for 3.3.0

**Closed** 2020-07-29 14:24 UTC

**Comment by songdavid98** [comment] 2020-08-09 12:14
It seems that Adventure 3.3.5 actually accepts this change. 

I don’t know how to reference it on mobile, so I'll just put the link here. 

https://github.com/aikaterna/gobcog/pull/281
