### ISSUE TITLE
Reward chests are lost if one was open when combat resolves

### ISSUE THREAD

**Issue by wlerin** [aikaterna/gobcog#27] opened 2019-04-23 21:46 UTC
If you start opening a chest before combat resolves (e.g. while it's still calculating or just before), and finish after the conflict resolves, and chests rewarded by that combat will be lost:

https://i.imgur.com/MdlJNsA.png

I'd guess the looting function uses a stale count to update the player's chests, but I haven't taken the time to confirm this in the code.

**Comment by TrustyJAID** [comment] 2019-05-06 19:48
So this is absolutely a race condition from two different config entries being written at the same time. The best way I can say to solve it is to tell people not to open chests right when an adventure is about to end. I might be able to add some checks for close to being finished adventures but I can't reliably reproduce to check since this is a moving target.

**Comment by wlerin** [comment] 2019-05-06 22:29
asyncio does have locks and similar mechanisms:
https://docs.python.org/3/library/asyncio-sync.html

Perhaps they might be of use?

**Comment by TrustyJAID** [comment] 2019-05-06 23:21
Yeah just worked on adding asyncio.lock() to every write. Should be added with #23 when it gets merged after I do some more testing.

**Closed** 2019-05-09 03:43 UTC
Labels: bug
