### ISSUE TITLE
[Bug] forging cant find Ascended items

### ISSUE THREAD

**Issue by sirenondine** [aikaterna/gobcog#294] opened 2020-08-11 18:00 UTC
when forging. if trying to give  the name of an ascended item adventure is unable to find it

## Complete these first
- [X] I confirm that I am the owner of the bot running Adventure.
- [X] I confirm that I have not modified the source code of Adventure.
- [ ] I'm an Adventure user but not the bot owner.
- [X] I confirm that I have checked the [issue tracker](../) and a this bug hasn't been reported already.

## Expected Behavior
Ascended items should be selectable. Or, if they cannot be forged they it should not show up as forgable

## Current Behavior
Adventure version: 3.3.6
Recieving an error @name  I could not find that item - check your spelling.

## Steps to Reproduce
1. equip an ascended item
2. be a tinkerer and start a forge
3. provide name of ascended item
4. error occurs

## Context (Environment)
Ascended items are failing to be recognized when forging. 
![Screenshot from 2020-08-11 12-52-05](https://user-images.githubusercontent.com/50174839/89932049-a7059f00-dbd2-11ea-84fa-631f2dfe9f96.png)
![Screenshot from 2020-08-11 12-53-09](https://user-images.githubusercontent.com/50174839/89932065-aa992600-dbd2-11ea-83be-a04fc6bfb2b1.png)

**Comment by Drapersniper** [comment] 2020-08-11 18:02
show the output of `[p]stats`

**Comment by sirenondine** [comment] 2020-08-11 18:09
![Screenshot from 2020-08-11 13-09-08](https://user-images.githubusercontent.com/50174839/89932875-e08ada00-dbd3-11ea-98df-787193c2916b.png)

**Comment by sirenondine** [comment] 2020-08-11 18:10
![Screenshot from 2020-08-11 13-10-44](https://user-images.githubusercontent.com/50174839/89933037-13cd6900-dbd4-11ea-95f1-e642422ff2e4.png)

**Comment by aikaterna** [comment] 2020-08-11 18:12
So it looks like if you are under 30 rebirths you will not be able to forge ascended items. This is working as intended, however this is confusing to users and I am going to look into adding text in that area that will alert players of this condition. I will close this issue with that commit after I look at it and see how feasable that is.

**Comment by sirenondine** [comment] 2020-08-11 18:28
Great thank you

**Closed** 2020-08-12 01:53 UTC
